### ISSUE TITLE
signup.htmlで再登録する際に，登録ボタンが薄くなってしまう

### ISSUE THREAD

**Issue by yuu-nkjm** [MAGCruise/magcruise-citywalk#160]
PC上のブラウザでは起こりませんが，Chrome on Androidで起こります．

以下は，Chromeのエミュレータモードのスクリーンショット．

![](https://i.gyazo.com/0ce0a721a93470ded7b6beb124113ede.png)

**Comment by yuu-nkjm** [comment]
この振る舞いは(bootstrapが備える)二重投稿防止機能のためと思います．
PINタスクでも，間違えて再入力するときも，同じようになった気がします(未確認)．

**Comment by yuu-nkjm** [comment]
common.cssの以下が悪さをしているようです．

```css
/*
a:hover {
  opacity: 0.6;
}

a:hover img {
  opacity: 0.6;
}
```
